spring:
  application:
    name: medassistant
  datasource:
    url: jdbc:postgresql://localhost:5432/medassistant
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop